- package.json
This configuration change fixes the color demo's in the Storybooks color page:
Typical case of "worked in dev"... `npm run storybook` was okay, `npm run build && npm run start` was not.
> build: include proprietary CSS in Storybook

- src/paragraph/README.md
- src/paragraph/html.scss
- src/paragraph/html.stories.mdx
- src/paragraph/index.css
- src/paragraph/stories.mdx
Voorzet voor de Paragraaf component #25
- **paragraph** omdat het de onafgekorte versie van het `<p>` element in HTML
- **lead** paragraph omdat het een [eigen lemma heeft op Wikipedia](https://en.wikipedia.org/wiki/Lead_paragraph). Eerst had ik "Intro paragraph" gekozen, omdat ik in code vaak `<p class="intro">` ben tegengekomen, maar het blijkt niet de gebruikelijke term te zijn.
- `utrecht-paragraph`
- `utrecht-paragraph--lead`
We gebruiken de volgende CSS variabelen:
Document (abstract component)
- `utrecht-document-font-family`
Paragraph:
- `utrecht-paragraph-font-size`
- `utrecht-paragraph-font-family`
- `utrecht-paragraph-font-size`
- `utrecht-paragraph-font-weight`
- `utrecht-paragraph-line-height`
- `utrecht-paragraph-margin-block`
Lead paragraph:
- …
> feat: paragraph component

- src/heading/README.md
- src/heading/html.scss
- src/heading/html.stories.mdx
- src/heading/index.css
- src/heading/stories.mdx
Voorzetje voor de Heading 1 - Heading 6 components (backlog: #22 en nl-design-system/backlog#114)
De documentatie voor de verschillende heading levels kan verschillen, het kan zijn dat wordt aangeraden de teksthierarchie te beperken tot en met niveau van h4. Veel design systeems raden af om heading-5 en heading-6 te gebruiken.
- "heading" uit [de HTML specificatie van `h1`/`h2`/`h3`/`h4`/`h5`/`h6`](https://html.spec.whatwg.org/multipage/sections.html#the-h1,-h2,-h3,-h4,-h5,-and-h6-elements). "h1" is nogal kortaf, daarom schrijven we "heading-1".
In HTML wordt de term "heading" gebruikt, niet "header" (dat is ook iets anders). Let dus op om niet per ongeluk "header" te schrijven in plaats van "heading".
- `utrecht-heading-1`
- `utrecht-heading-2`
- `utrecht-heading-3`
- `utrecht-heading-4` …
> feat: heading components

- src/link/README.md
- src/link/docs/accessibility-guidelines.md
- src/link/html.scss
- src/link/link-html.stories.mdx
- src/link/link.stories.mdx
- src/link/style.css
Meer varianten en meer design tokens voor de Link component #26 nl-design-system/backlog#118 
De termen de we gebruiken komen uit HTML en CSS.
- link (`:link` in CSS, "hyperlink" in de HTML specificatie)
- active (`:active` in CSS)
- focus (`:focus` in CSS)
- hover (`:hover` in CSS)
- visited (`:visited` in CSS)
Voor de component naam hebben we voor "`link`" gekozen, en niet voor "`a`" zoals de [`<a>`](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element) in HTML. Buiten de context van HTML-code (bijvoorbeeld in Figma) is `a`niet duidelijk genoeg, en we verwachten niet dat er grote verwarring ontstaat met het [`<link>`](https://html.spec.whatwg.org/multipage/semantics.html#the-link-element) element van HTML.
We hebben de volgende states:
- normal
- hover
- focus …
> feat: link component

- src/separator/README.md
- src/separator/html.scss
- src/separator/html.stories.mdx
- src/separator/index.css
- src/separator/stories.mdx
Voorzet voor de Separator component (backlog: #23, nl-design-system/backlog#119).
- **separator**, van de ARIA `role="separator"`. "hr" van `<hr>` uit HTML is te onduidelijk buiten de context van code, "horizontal rule" te specifieke beschrijving van de originele rendering in HTML. De "separator" zou er ook heel anders uit kunnen zien dan een "rule" (lijn), en bovendien kan er voor andere tekstrichtingen wel eens een verticale variant komen.
"Divider" is ook een vaak gehoorde term hiervoor, misschien moet deze voor vindbaarheid ook genoemd worden in de documentatie.
Niet van toepassing.
- `utrecht-separator`
- horizontaal
We hebben de volgende CSS variabelen:
- `utrecht-separator-color`
- `utrecht-separator-width` - "width" is misschien verwarrend, voor de horizontale variant is "height" …
> feat: separator component

- .lintstagedrc.json
Couple of days ago I added `.css` file that in a directory listed in `.stylelintignore`, which caused the pre-commit hook to fail because the lint tool errored with "no files matched the specified pattern". Allowing no matching files for the lint-staged commands will prevent that.
> config: avoid pre-commit error for files in ignore list

- proprietary/design-tokens/common/document.css
- proprietary/design-tokens/component/index.css
- proprietary/design-tokens/component/unordered-list.css
- src/unordered-list/README.md
- src/unordered-list/html.scss
- src/unordered-list/html.stories.mdx
- src/unordered-list/index.css
- src/unordered-list/stories.mdx
Voorzet voor de Unordered list component #24
- **unordered list**: uitgeschreven versie van de HTML afkorting `<ul>`
- **list item**: uitgeschreven van van [HTML `<li>`](https://html.spec.whatwg.org/multipage/grouping-content.html#the-li-element). Ook [in ARIA is het `role="listitem"`](https://www.w3.org/TR/wai-aria-1.2/#listitem)
- **marker**: zoals in de [CSS pseudo-selector `::marker`](https://drafts.csswg.org/css-pseudo-4/#marker-pseudo)
- `utrecht-unordered-list`
- `utrecht-unordered-list--distanced`: standaard heeft een component geen marge, gebruik deze class name om in een bepaalde context de standaard-marge toe te passen
- `utrecht-unordered-list--nested`
- `utrecht-unordered-list__item`: misschien moet nog aangepast worden naar `utrecht-unordered-list__listitem` of - …
> feat: unordered list

- proprietary/design-tokens/component/blockquote.css
- proprietary/design-tokens/component/index.css
- src/blockquote/README.md
- src/blockquote/html.scss
- src/blockquote/html.stories.mdx
- src/blockquote/index.css
- src/blockquote/stories.mdx
Voorzetje voor de Blockquote component (backlog: #28 en nl-design-system/backlog#73).
- **blockquote**: van het [HTML element `<blockquote>`](https://html.spec.whatwg.org/multipage/grouping-content.html#the-blockquote-element). MDN noemt het ["Block Quotation element"](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blockquote), misschien zou dat nog wel beter zijn dan "Blockquote".
- **content**: ik sta open voor suggesties.
- **attribution**: verwijzing naar de bron van het citaat. Alternatieven welkom.
- `utrecht-blockquote`: container element
- `utrecht-blockquote__content`: gedeelte waar het citaat word genoemd
- `utrecht-blockquote__attribution`: gedeelte waar de bron van het citaat word genoemd
- `utrecht-blockquote--distanced`: modifier om afstand te creëren tot …
> feat: blockquote component

- components/heading/README.md
- components/heading/index.css
- proprietary/design-tokens/src/component/_heading.scss
The heading in the page footer component needs a custom `text-transform`:
This PR includes the `text-transform` design token for every heading level (1-6).
Aditionally the Heading 5 and Heading 6 in the regular body text also need text-transform. For this the design token was already defined in the theme even though the component didn't support it yet.
Investigating this I also noticed the font-weight was incorrectly bold for h3-h6.
> feat: add `text-transform` design tokens for headings

- components/alternate-lang-link/README.md
- components/alternate-lang-link/bem.css
- components/alternate-lang-link/bem.stories.mdx
- components/alternate-lang-link/html.scss
- components/alternate-lang-link/html.stories.mdx
- components/alternate-lang-nav/README.md
- components/alternate-lang-nav/stories.mdx
- components/html-content/html.scss
Voorzetje voor de taal-link component #107 nl-design-system/backlog#140.
Wat nu nog ontbreekt:
- CSS styling
- documentatie over class names
- argumentatie over gekozen terminologie
> feat: alternate language navigation

- packages/web-component-library-stencil/package.json
there was a problem in my system because it is windows and that problem is now solved
> fix: make `npm run storybook` work on windows

- .gitignore
Files generated by JetBrains IDEs were are not yet present in the gitignore. This PR adds the `.idea/` folder to the gitignore.
> fix: add .idea to .gitignore

- documentation/space.stories.mdx
Stumbled across a very confusing mixup of these two words while reading the docs for spacing tokens
> docs: use correct orientation terms for spacing

- .patches/@stencil+core+2.9.0.patch
- package-lock.json
- package.json
- packages/web-component-library-stencil/README.md
In order to support `Content-Security-Policy` without `unsafe-inline`, the `<style>` elements from Stencil must contain a `nonce` attribute. The nonce value must be generated randomly for every page request. In order to for Stencil to know what nonce to use, this patch will make Stencil look for any existing `<style nonce="123...">` attributes, and copy the value.
In order to use the Web Components with CSP (and CSP is always a good idea) include the following in the `<head>` of your page:
```html
<html>
<head>
<style nonce="RANDOMLY-GENERATE-THIS-STYLE-NONCE"></style>
<script nonce="RANDOMLY-GENERATE-THIS-SCRIPT-NONCE"></script>
```
You can use empty tags like the example above, but a nonce on any `style` element will work as long as it is available before the web component code is …
> fix: patch Stencil to copy nonce for <style> elements

- components/link/bem.scss
- components/link/tokens.json
- components/paragraph/README.md
- documentation/link.stories.mdx
- proprietary/design-tokens/src/component/utrecht/link.tokens.json
- proprietary/design-tokens/src/component/utrecht/paragraph.tokens.json
`a:hover` in a paragraph:
some findings:
`text-decoration-skip` can be helpful to avoid making some texts unreadable.
For example by obscuring Arabic diacritics.
However, the combination of a greater thickness and skipping this thick underline
leads to a very unappealing rendering of the underline. To avoid this,
`text-decoration-skip` is disabled for interactive states.
For design token configurations that have identical thickness for normal and interactive
states, this will lead to the (undesirable) effect that the focus/hover effect is switching
from an interrupted to an uninterrupted underline (for some texts).
Apart from making `skip-ink` configurable for normal/focus/hover, there is no good solution yet.
---
Disabling `text-decoration-skip` for interactive states obscures some …
> feat: text-decoration-thickness design tokens for Link

- packages/storybook/config/preview-head.html
- packages/storybook/config/preview.js
Since adding a decorator breaks stories with HTML templates in strings, and only seems to work when all stories use JSX, I am using a new approach to add the `utrecht-theme` class name to the documents.
> fix: provide design tokens to all Storybook pages

- components/navigatie sidenav/bem.scss
Voor de CSS component van Sidenav werd het bolletje donkerblauw, maar voor de web component (die net iets anders werkt) gebeurde er niets bij `:hover`. Dat is nu gefixt.
> style: fix web component sidenav hover

- .eslintignore
- .prettierignore
- package-lock.json
- standalone/docusaurus/docusaurus.config.js
- standalone/docusaurus/package.json
- standalone/docusaurus/src/theme/SearchBar/algolia.css
- standalone/docusaurus/src/theme/SearchBar/index.js
- standalone/docusaurus/src/theme/SearchBar/lib/DocSearch.js
- standalone/docusaurus/src/theme/SearchBar/lib/lunar-search.js
- standalone/docusaurus/src/theme/SearchBar/lib/templates.js
- standalone/docusaurus/src/theme/SearchBar/lib/utils.js
- standalone/docusaurus/src/theme/SearchBar/styles.css
While we're waiting for the nice people from Algolia to grand us free access to their crawler services, let's try one of the local search packages from https://docusaurus.io/docs/search#using-local-search
🎉 Tada: local search works after build.
**Note**: it doesn't work during development with `npm run docs` but it does work out of the box after deployment and with `npm run build:docs && npm run serve:docs` locally
https://user-images.githubusercontent.com/877246/153872649-73af896c-98e0-493f-b043-04ad877e673a.mp4
> feat: add local search

- .commitlintrc.json
- .huskyrc.json
- package-lock.json
- package.json
Je kunt commit messages testen met:
- `echo 'fix: foo' | npx commitlint` of bijvoorbeeld:
- `npx commitlint --from=a089b60b6bfdc687f6d8d9e3fe09930605681b80`
> ci: install commitlint to enforce conventional commits

- .github/workflows/continuous-delivery.yml
For pulling and pushing to the `main` branch, we now use an access token from the `nl-design-system-ci` user. We have configured this repository to make `nl-design-system-ci` the exception to the branch protection rules.
While most steps will have access to the `GITHUB_TOKEN` from the environment, we make `GH_TOKEN` available with special permissions. We only configure the `GH_TOKEN` for the main branch, so only scripts that have been reviewed by folks with merge rights will have access to it.
> ci: use higher-permission token for releases

- .github/workflows/continuous-delivery.yml
Follow up to PR #752.
The previous commit did not appear to be sufficient, and the GitHub branch protection configuration was not accurat. It resulted in the following error in the release script:
```text
lerna info git Pushing tags...
[36](https://github.com/nl-design-system/utrecht/runs/5350620083?check_suite_focus=true#step:6:36)
lerna ERR! Error: Command failed with exit code 1: git push --follow-tags --no-verify --atomic origin main
[37](https://github.com/nl-design-system/utrecht/runs/5350620083?check_suite_focus=true#step:6:37)
lerna ERR! remote: error: GH006: Protected branch update failed for refs/heads/main.        
[38](https://github.com/nl-design-system/utrecht/runs/5350620083?check_suite_focus=true#step:6:38)
lerna ERR! remote: error: You're not authorized to push to this …
```
> ci: use higher-permission token for release job only

- .github/workflows/continuous-delivery.yml
This PR aims to provide infrastructure to publish a snapshot of the documentation to a separate repository. The current approach here seems to work, the main thing missing from this setup is that the version number is not readily associated with the snapshot of the documentation.
Ideally the docs have a version number in the code, as well as git tags for the commit that is pushed to the other repository. Since at the version number is not yet known in job that runs parallel to `publish-npm`, this would mean some further refactoring that would include:
- (re)building the docs after the version has been released
- using method other than [JamesIves/github-pages-deploy-action](https://github.com/JamesIves/github-pages-deploy-action) to deploy the code, since it doesn't offer a parameter to …
> ci: deploy docs to separate repo

- .gitattributes
- components/icon/package.json
- package-lock.json
- Prettier didn't gave errors for basically  every file because the newline endings were incorrect, configuring `.gitattributes` with a strict line feed setting did help
- `mkdir -p` does not work on Windows, so use a utility for that
Other remaining issues, which we'll need to look in some other time, are:
- docusaurus tmp/ folder appears to be empty, causing file imports not to be found
- `stylelint '**/*.{css,scss}'` works on Mac, `stylelint **/*.{css,scss}` works on Windows, but neither works on both
- `npm run lint:html` relies on Linux utility `find`, which won't work on Windows — I have no solution in mind for this yet
- `markdownlint` doesn't appear to find any files — I have no solution in mind for this yet
- `eslint --ext '.js,.json,.jsx,.mdx,.ts,.tsx' .` on Windows doesn't find …
> build: fix some lint and installation errors on Windows

- standalone/docusaurus/docusaurus.config.js
Somehow breadcrumbs where added to Docusaurus, but we didn't design them or choose them. By setting breadcrumbs to false they are gone 🔥
> docs: remove new unwanted breadcrumbs from documentation

- components/button/bem.scss
- components/button/tokens.json
Turns out we had the border-width token, but no way to configure the color of the border. 
Gemeente Buren had no way to correctly to correctly style their secondary button, this should fix that.
> feat(button): border-color design token

- components/process-steps/react.stories.mdx
For some unknown reason the denhaag-process-steps components cause `<Story/>` to render `[object Object]` instead of the component. There are no other errors and I haven't found a fix (yet).
By not using `Story` and directly putting the code in `Canvas` it displays the component and the `view source` button with the correct source. This seems like a good MVP for now
> docs: quick fix to display process steps code snippet in canvas

- components/alternate-lang-nav/css/stories/default.stories.mdx
- components/alternate-lang-nav/css/stories/readme.stories.mdx
- components/alternate-lang-nav/css/template.js
- components/alternate-lang-nav/readme.stories.mdx
> refactor: rename bem to css and group implementations

- components/radio-button/html/template.js
- components/select/html/template.js
- package.json
- fix error when starting Storybook that would require to run `npm run build` manually once
- fix JavaScript errors in developer console when running Storybook
> fix: minor Storybook fixes

- .stylelintrc.json
- components/button/css/_mixin.scss
- components/button/css/stories/02-appearance.js
- proprietary/design-tokens/src/component/utrecht/button.tokens.json
The complexity of the code to support various appearances got out of hand, and it was difficult to support all the various states for each appearance. This should help.
I suspect the approach was inspired by an article by Lea Verou I had read some time last year: [Custom properties with defaults](https://lea.verou.me/2021/10/custom-properties-with-defaults/#bonus-customizable-single-checkbox-pure-css-switch)
> refactor: button CSS now uses private CSS variables

- standalone/docusaurus/docusaurus.config.js
Ik ben begonnen met de `Content-Security-Policy` van pki.utrecht.nl, en heb 'm wat stricter gemaakt door overal `https:` weg te halen zodat niet elke domeinnaam is toegestaan.
Twee dingen staan nu in de allow lists:
- `nl-design-system.github.io` voor de Storybook iframes. Idealiter gaat deze eruit en worden de stories altijd op hetzelfde domein gehost
- Algolia domeinen volgens de [Algolia Security Best Practices](https://www.algolia.com/doc/guides/security/security-best-practices/#content-security-policy), zodat de search werkt.
> build: add `Content-Security-Policy` to Docusaurus

- .husky/commit-msg
- .husky/pre-commit
- .huskyrc.json
Husky hasn't been working for a while now, the update to Husky 8 should have included our migration to the new way of configuring Husky.
> ci: migrate Husky configuration to Husky 8

- packages/storybook-vue/src/stories/RadioButton/RadioButtonWithFieldsetAndLegend.stories.mdx
- packages/storybook-vue/src/stories/RadioButton/RadioButtonWithLabel.stories.mdx
[Reference:](https://www.w3.org/TR/WCAG20-TECHS/G162.html#:~:text=Labels%20for%20most%20fields%20are,are%20positioned%20after%20the%20field)
> docs: move the label after the field

- packages/storybook/stories/css-component/combining-components/inline-link.stories.mdx
For the upcoming WCAG rules the links should be at least 24x24px, or if they are smaller, there should be enough space between links that link size + space is at least 24 pixels.
Currently these stories demonstrate that the distance is not yet large enough, and we should increase the line-height.
> docs: stories to show link distances in unordered list

- components/textbox/css/index.scss
- components/textbox/html/index.scss
- packages/component-library-react/src/Textbox.test.tsx
- packages/component-library-react/src/Textbox.tsx
The reason to minimize using javascript to deal style
**reference to the issue:**
https://github.com/nl-design-system/utrecht/blob/main/packages/component-library-react/src/Textbox.tsx#L33
> feat: textbox support `[attribute="value"]` in css

- components/digid-button/css/index.scss
- components/digid-logo/web-component/index.scss
- components/eherkenning-logo/web-component/index.scss
- components/eidas-logo/web-component/index.scss
- components/logo-button/css/index.scss
- components/logo/css/_mixin.scss
- components/logo/tokens.json
- proprietary/design-tokens/src/component/utrecht/logo.tokens.json
To make the logo actually visible it helps a lot to be able to specify some minimum size.
> refactor: logical tokens and minimum size for logo

- packages/docusaurus/src/styles/custom.scss
We wilden nog graag "Iets slims kunnen doen met de breedte van de afbeeldingen, want ze schalen nog niet echt mooi"
Ik heb nu in docusaurus `custom.scss` `height: auto` toegevoegd en dat lijkt prima te werken voor zover ik kan zien
```css
img {
height: auto;
}
```
> docs: fix images in docusaurus

- components/data-list/css/_mixin.scss
- proprietary/design-tokens/src/component/utrecht/data-list.tokens.json
Addition to the data-list styling that enables the Den Haag definition-list to be emulated without breaking the existing styling of the data-list.
> style: allowing for shared properties for data lists

- components/blockquote/css/_mixin.scss
- components/blockquote/tokens.json
- proprietary/design-tokens/src/component/den-haag/process-steps.tokens.json
- proprietary/design-tokens/src/component/utrecht/blockquote.tokens.json
- proprietary/design-tokens/src/style-dictionary-config.js
- proprietary/design-tokens/style-dictionary.config.json
It is quite usual to have a `background-color` for blockquotes, which would also require a matching `color`. The RVO blockquote design requires this. When there is a background image, it makes sense to have a padding around the text. Quotes are frequently rendered as italic, so include `font-style` too.
> feat: new design tokens for blockquote

- components/link-social/css/_mixin.scss
- components/link-social/css/index.scss
- components/link-social/css/stories/distanced.stories.mdx
- components/link-social/css/stories/state.stories.mdx
- components/link-social/css/story-template.jsx
- components/link-social/tokens.json
For Den Haag we also need social-link and social-link-list components. We can use these Utrecht components but we don't change the size of the icons on hover but the background-color instead. 
We could continue with the Utrecht CSS if we had a mixin
It would be ideal to have the states in Storybook to see how Utrecht has implemented these without using the inspector
If Utrecht doesn't mind we could also add the API's to the Utrecht component directly
> feat: improve social link

- components/link/css/_mixin.scss
- components/link/tokens.json
- proprietary/design-tokens/src/component/utrecht/link.tokens.json
Would be very helpful for Haarlem.
Eventually we probably need text-decoration-color tokens for interactive states too.
---
- Ik heb de nieuwe token toegevoegd voor de underline kleur, omdat voor Haarlem die lichtgrijs moet zijn (en dat was geen optie met de bestaande component)
- Ik heb de token van text-underline-tickness aangepakt omdat jullie terecht hadden gezegd dat 'ie in CSS text-decoration-thickness heet
> feat: add `text-decoration-color` token for links

- components/navigatie sidenav/README.md
- components/navigatie topnav/README.md
- components/navigatie topnav/css/index.scss
This PR updates:
- the usage of the sans-serif token in the navigatie topnav to --utrecht-document-font-family.
- the README for topnav which mentions the use of the token
- the README for sidenav which mentions the same token (though it does not appear in the CSS?)
Fixes https://github.com/nl-design-system/utrecht/issues/1566
> Update font token

- packages/storybook-react/src/stories/Alert.stories.tsx
- packages/storybook-react/src/stories/Article.stories.tsx
- packages/storybook-react/src/stories/Backdrop.stories.tsx
- packages/storybook-react/src/stories/ButtonGroup.stories.tsx
- packages/storybook-react/src/stories/Code.stories.tsx
- packages/storybook-react/src/stories/CodeBlock.stories.tsx
- packages/storybook-react/src/stories/Mark.stories.tsx
- packages/storybook-react/src/stories/NumberValue.stories.tsx
- packages/storybook-react/src/stories/PreHeading.stories.tsx
- packages/storybook-react/src/stories/Separator.stories.tsx
- packages/storybook-react/src/stories/Strong.stories.tsx
Duplicate of #1638 but rebased onto main, to see if it fixes non locally reproducible lint errors.
> refactor: use CSF3 and Storybook 7 types for more react components

- components/button/tokens.json
- components/common/focus/tokens.json
- components/common/pointer-target/tokens.json
- components/form-control/README.md
- components/form-control/css/stories/readme.stories.mdx
- components/form-control/css/stories/tokens.stories.mdx
- components/form-control/tokens.json
- components/form-input/README.md
- components/heading-1/tokens.json
- components/heading-2/tokens.json
- components/heading-3/tokens.json
- components/heading-4/tokens.json
- components/heading-5/tokens.json
- components/heading-6/tokens.json
- components/link/tokens.json
- components/paragraph/tokens.json
- components/select/css/_mixin.scss
- components/textarea/css/_mixin.scss
- components/textbox/css/_mixin.scss
- proprietary/design-tokens/src/common/utrecht/pointer-target.tokens.json
- proprietary/design-tokens/src/component/utrecht/custom-checkbox.tokens.json
- proprietary/design-tokens/src/component/utrecht/form-control.tokens.json
- proprietary/design-tokens/src/component/utrecht/form-field.tokens.json
- proprietary/design-tokens/src/component/utrecht/radio-button.tokens.json
BREAKING CHANGE: `--utrecht-form-input` CSS variables no longer work
> refactor: rename `form-input` tokens to `form-control`

- packages/component-library-react/src/Calendar/index.tsx
Solves https://github.com/frameless/utrecht-huwelijksplanner/issues/265
Clicking a date from a previous month would select that same day in the current month. This change correctly changes the current day to the selected day. This also fixes a bug where selecting 31st March when April is the active month would change the calendar to May. It now correctly switches to 31st March.
> fix: allow selecting dates from previous and next month

- components/calendar/css/_mixin.scss
- packages/component-library-react/src/Calendar/index.tsx
- proprietary/design-tokens/src/component/utrecht/calendar.tokens.json
Based on https://github.com/nl-design-system/utrecht/pull/1699
This change adds styling to the calendar days for the following states
- Is today
- Is selected
- Is disabled
[Figma design](https://www.figma.com/file/msb3CfQBefPoruqNQ968Zh/Utrecht-Design-System?node-id=2903-6360&t=VAIWYtcANbzpWIkn-0)
> feat: datepicker table body styling

- packages/component-library-react/src/Calendar/index.tsx
- packages/storybook-react/src/stories/Calendar.stories.tsx
- Adds default no selection to datepicker
- Allows navigating to different month / year without losing day selection
- Removes onCalendarClick callback trigger when navigating
> feat: allow unselected date and keep date when navigating months

- proprietary/design-tokens/src/background-image-icon.scss
- proprietary/design-tokens/src/dark/index.scss
- proprietary/design-tokens/src/index.scss
- proprietary/design-tokens/src/style-dictionary-config-dark.js
- proprietary/design-tokens/style-dictionary.config.json
This reverts commit fb62efec0a5681efdf8d142d25a6ecbdecb23cf8.
Unfortunately the following code makes the user selection invisible:
```
::selection {
--color: red;
}
```
Somehow, only having a custom property, breaks `background-color` and `color`. This totally works:
```
::selection {
--color: red;
background-color: Highlight;
color: HighlightText;
}
```
However, the following would not be our intention:
```
.utrecht-theme,
.utrecht-theme ::selection {
--color: red;
background-color: Highlight;
color: HighlightText;
}
```
Perhaps we could do the following, but I doubt it would be worth the complexity.
```
.utrecht-theme,
.utrecht-theme ::selection {
--color: red;
}
.utrecht-theme ::selection {
background-color: Highlight;
color: HighlightText;
}
```
> fix: revert "support design tokens in `::selection`"

- components/button/tokens.json
> fix: replace "transform" with "scale" in the button tokens json file

- packages/component-library-react/src/FormLabel.tsx
- packages/storybook-react/src/stories/BadgeList.stories.tsx
- packages/storybook-react/src/stories/BreadcrumbNav.stories.tsx
- packages/storybook-react/src/stories/Button.stories.tsx
- packages/storybook-react/src/stories/ColorSample.stories.tsx
- packages/storybook-react/src/stories/FormField.stories.tsx
- packages/storybook-react/src/stories/FormLabel.stories.tsx
- packages/storybook-react/src/stories/OrderedListItem.stories.tsx
- packages/storybook-react/src/stories/Select.stories.tsx
- packages/storybook-react/src/stories/UnorderedListItem.stories.tsx
- packages/storybook-react/src/stories/template/PageStep-1.stories.tsx
- packages/storybook-react/src/stories/template/PageStep-2.stories.tsx
- packages/storybook-react/src/stories/template/PageStep-3.stories.tsx
- packages/storybook-react/src/stories/template/PageStep-4.stories.tsx
- packages/storybook-react/src/stories/template/PageStepLogin.stories.tsx
- packages/storybook-react/src/stories/util.tsx
- packages/storybook-react/src/utrecht-design-tokens.d.ts
Still some errors remaining, mostly to do with `subcomponents` and with `render: ...` typing:
```text
Found 89 errors in 13 files.
Errors  Files
1  ../../node_modules/.pnpm/markdown-to-jsx@7.1.8_react@18.2.0/node_modules/markdown-to-jsx/dist/index.d.ts:53
1  src/stories/AlternateLangNav.stories.tsx:16
1  src/stories/ButtonGroup.stories.tsx:13
3  src/stories/FormField.stories.tsx:22
13  src/stories/FormFieldCheckbox.stories.tsx:85
18  src/stories/FormFieldCheckboxGroup.stories.tsx:74
15  src/stories/FormFieldRadioGroup.stories.tsx:74
13  src/stories/FormFieldText.stories.tsx:78
2  src/stories/Icon.stories.tsx:21
6  src/stories/Page.stories.tsx:17
2  src/stories/RadioButton.stories.tsx:14
13  src/stories/Select.stories.tsx:84
1  src/stories/util.tsx:2
```
> docs: fix typescript errors in Storybook React stories

- components/calendar/css/_mixin.scss
font-weight was misspelled, causing the style overrides not to be picked up.
> fix: typo in CSS property

- .github/workflows/continuous-delivery.yml
Currently the build fails:
```
lerna-lite notice cli v1.17.0
lerna-lite info versioning independent
lerna-lite info ci enabled
lerna-lite info Assuming all packages changed
lerna-lite ERR! EUNCOMMIT Working tree has uncommitted changes, please commit or remove the following changes before continuing:
lerna-lite ERR! EUNCOMMIT  M pnpm-lock.yaml
lerna-lite ERR! Working tree has uncommitted changes, please commit or remove the following changes before continuing:
lerna-lite ERR!  M pnpm-lock.yaml
 ELIFECYCLE  Command failed with exit code 1.
```
> ci: use frozen lockfile with new pnpm

- packages/component-library-react/tsconfig.json
- packages/component-library-vue/tsconfig.jest.json
- packages/component-library-vue/tsconfig.lib.json
- packages/component-library-vue/tsconfig.vite-config.json
- packages/storybook-helpers/tsconfig.json
- packages/storybook-react/tsconfig.node.json
- packages/storybook-vue/tsconfig.node.json
- packages/web-component-library-vue/tsconfig.app.json
- packages/web-component-library-vue/tsconfig.vite-config.json
Bug report via Slack:
> In de laatste versies van  @utrecht/component-library-react krijg ik de volgende foutmelding wanneer ik (voor de PRA) mijn component-library-react probeer te "builden":
> `Could not find a declaration file for module '@utrecht/component-library-react/dist/css-module'.`
> In de node_modules/@utrecht/component-library-react/dist folder zie ik de componenten van Utrecht niet meer en ook zie ik het index.d.ts bestand niet.
> Klopt het dat de componenten het index.d.ts bestand in deze folder ontbreken?
> (Het lijkt te komen door de `"composite": true` in `tsconfig.json`)
Conclusie: `composite: true` stelt de `rootDir` aan in op de locatie van `tsconfig.json`, dus de file is onbedoeld verplaatst van `dist/css-module/index.d.ts` naar `dist/src/css-module/index.d.ts`.
De …
> build: always specify rootDir when composite: true

- components/button/css/_mixin.scss
- components/button/tokens.json
- components/heading-1/css/_mixin.scss
- components/heading-2/css/_mixin.scss
- components/heading-3/css/_mixin.scss
- components/heading-4/css/_mixin.scss
- components/heading-5/css/_mixin.scss
- components/heading-6/css/_mixin.scss
- components/link-button/css/_mixin.scss
- components/pre-heading/css/_mixin.scss
- components/search-bar/css/_mixin.scss
- components/search-bar/tokens.json
- documentation/website/huisstijl/typography.md
- proprietary/design-tokens/src/brand/utrecht/typography.tokens.json
- proprietary/design-tokens/src/component/utrecht/heading-1.tokens.json
- proprietary/design-tokens/src/component/utrecht/heading-2.tokens.json
- proprietary/design-tokens/src/component/utrecht/heading-3.tokens.json
- proprietary/design-tokens/src/component/utrecht/heading-4.tokens.json
- proprietary/design-tokens/src/component/utrecht/heading-5.tokens.json
- proprietary/design-tokens/src/component/utrecht/heading-6.tokens.json
- proprietary/design-tokens/src/component/utrecht/search-bar.tokens.json
The `letter-spacing` were only used with `text-transform: uppercase`, without they should be discouraged.
> style: remove `letter-spacing` tokens (except for badge)

- components/skip-link/css/_mixin.scss
Use `ButtonFace` as default `background-color` to ensure the skip link is not transparent and unreadable when CSS variables are not defined.
My only concern with this is that it makes it look like a button, and it implies the `Space` button should work, but it won't work. But I consider this a smaller usability issue than no background.
> style: avoid unreadable overlapping skip links

- packages/storybook-react/config/main.ts
- packages/storybook-react/config/preview.tsx
- packages/storybook-vue/config/main.ts
- packages/storybook-vue/config/preview.tsx
https://github.com/storybookjs/storybook/issues/15391
> docs: re-enable `addon-jest` with Vite workaround

- components/breadcrumb/css/_mixin.scss
- components/breadcrumb/tokens.json
- packages/storybook-css/src/BreadcrumbNav.stories.tsx
- packages/storybook-css/src/BreadcrumbNavAlternate.stories.tsx
- proprietary/design-tokens/src/component/utrecht/breadcrumb.tokens.json
rename `breadcrumb.separator.icon.color` to `breadcrumb.separator.color`
allow coloring text separators as well as icons
> style: rename breadcrumb separator color design token

- .changeset/angry-fans-move.md
- components/button/css/_mixin.scss
The text in the button would move one pixel or so when hovering.
> style: fix rendering glitch in Firefox when hovering over a button

- components/data-list/css/_mixin.scss
- components/data-list/tokens.json
For the designs of the WMEBV example form the data-list items should have padding defined.
I propose to add it here and make it available in the webcomponent.
https://www.figma.com/file/iIr1gkAR3oZ0UFWKIni8Nv/VNG---WMEBV---Templates?type=design&node-id=615-17736&mode=dev
> feat: add padding to data-list item

- .prettierignore
- package.json
- project.json
cached files and www files are now being ignored when prettier and lint:html are being run
> chore: exclude generated files from linting

- components/package.json
- packages/component-library-css/package.json
- packages/component-library-react/package.json
Previously the 2.0.0 version was released to npm, but not merged into main. Now 2.0.0 is accedintally an older release than 1.0.2-alpha.10. This release should fix that.
> build: update version numbers

- .github/CODEOWNERS
- .github/dependabot.yml
Enables us to easily add and remove people from 'dependabot review duty' and a step in the right direction to remove the root `kernteam-sysadmin`
> ci: change review teams

- .github/dependabot.yml
- .github/workflows/continuous-delivery.yml
- actions/upload-artifact and actions/download-artifact should always have the same major version
- prevent dependabot from opening separate PRs to update these dependencies
This should fix https://github.com/nl-design-system/utrecht/actions/runs/7816568086/job/21322825042
> build: bump actions/download-artifact

- packages/storybook-css/package.json
- packages/storybook-html/package.json
- packages/storybook-vue/package.json
- packages/storybook-web-component/package.json
- packages/storybook/package.json
- pnpm-lock.yaml
http-server was not installed but npx was used instead. This resulted in
> `sh: line 1: http-server: command not found`
> chore: add missing http-server in packages

- .ncurc.major.js
- .ncurc.minor.js
- .ncurc.patch.js
- package.json
Move the configuration from command line arguments into `.ncurc.patch.js` and override the necessary values in `.ncurc.minor.js` and `.ncurc.major.js`.
Clean up `package.json`.
> chore: simplify npm-check-updates configuration

- packages/component-library-react/src/Combobox.test.tsx
- packages/component-library-react/src/Combobox.tsx
- packages/component-library-react/src/Listbox.test.tsx
- packages/component-library-react/src/Listbox.tsx
`ref={ref}` support is needed for [implementing Downshift](https://github.com/downshift-js/downshift).
> feat: add `ForwardRef` to Combobox and Listbox components

- components/accordion/css/_mixin.scss
Browser default for the button is to align text in the center. This means that text is visibly center aligned when the button is full-width in the accordion.
> style: accordion text align

- components/form-toggle/css/_mixin.scss
- components/form-toggle/css/index.scss
- packages/component-library-react/src/FormToggle.tsx
We got a bug report that the cursor wasn't configurable, turns out the `<label>` overrides the `cursor` in the form toggle component.
> fix: activate cursor for React Form Toggle

- .github/workflows/continuous-delivery.yml
- update actions to their latest versions
- make action versions explicit
- re-order "pnpm/action-setup" and "actions/setup-node" so "actions/cache" is no longer needed
> build: update actions

- components/breadcrumb-nav/css/_mixin.scss
- components/breadcrumb-nav/css/index.scss
- packages/storybook-css/src/BreadcrumbNav.stories.tsx
Naar aanleiding van een vraag in Slack: https://codefornl.slack.com/archives/C01DAT4TRPF/p1715946802625149
> Ik gebruik het BreadcrumbNav component van de Gemeente Utrecht.
> Maar ik zie een verschillende cursors voor normale NavLinks en voor de huidige / "current" NavLink.
> Als ik over de NavLinks hover met mijn cursor krijg ik de “pointer” cursor (vanuit de user agent stylesheet).
> Maar bij het huidige / “current” NavLink Item krijg ik de pointer vanuit het --utrecht-action-inert-cursor token. (in mijn geval de default pointer)
> Zit er een reden achter het verschil voor de “current” NavLink en de andere NavLink’s?
> style: use "inert" cursor only for disabled current links

- components/select/css/_mixin.scss
- components/select/tokens.json
This is a breaking change for folks who have select components smaller than 44px, should I be more careful?
Het gaat om deze stories:
- [CSS Storybook — Select](https://utrecht-git-style-select-min-block-size-nl-design-system.vercel.app/storybook-css/index.html?path=/docs/css-select--docs)
- [CSS Storybook — Select design tokens](https://utrecht-git-style-select-min-block-size-nl-design-system.vercel.app/storybook-css/index.html?path=/story/css-select--design-tokens)
> style: add `min-block-size` to select and make the default minimum 44px

- components/alert/src/tokens.json
`utrecht-alert--info` exists in code but was not defined in the `tokens.json` despite being defined in the Utrecht theme.
> chore: update alert/tokens.json

- .changeset/chatty-islands-refuse.md
- .changeset/clean-ways-guess.md
- .changeset/early-needles-knock.md
- .changeset/ten-plums-reply.md
- .changeset/wet-coins-study.md
- .changeset/wise-students-swim.md
- components/link-list/src/_mixin.scss
- components/link-list/src/index.scss
- components/link-list/src/tokens.json
- packages/component-library-react/src/LinkList.tsx
- packages/storybook-css/src/PageFooter.stories.tsx
- proprietary/design-tokens/src/component/utrecht/link-list.tokens.json
This is part of getting the [Link list in the NL Design System community Figma](https://www.figma.com/design/gX3fq7k0uUKC45AJbuItDv/Local---Voorbeeld---Bibliotheek?node-id=1548-6863&t=KuOvWHVyjBq0moFp-4) consistent with the code from the Utrecht community component.
See also: [Link list GitHub discussion at NL Design System](https://github.com/orgs/nl-design-system/discussions/266)
> style: add link-list.row-gap token and other link list tweaks

- packages/component-library-react/src/IndexCharNav.test.tsx
- packages/component-library-react/src/IndexCharNav.tsx
Voorkomt dit soort rare situaties:
Arabic:
Chinese (Traditional):
Ik moest enkele bestaande unit tests refactoren om dit mogelijk te maken.
> fix: avoid translation of index characters

- .changeset/dry-rats-dress.md
- .changeset/tough-apricots-drum.md
- components/button/src/_mixin.scss
- components/button/src/tokens.json
Resolves #2236 and #1828.
De mogelijkheden zijn nu eindeloos! Maar het belangrijkste is natuurlijk dat de oranje DigiD button nu 18.6667px kan zijn in plaats van 18px om voor een Status A bij het DigiToegankelijk Dashboard.
> feat: button appearance font-size and line-height tokens

- components/icon/src/svg/chevron-left.svg
- components/icon/src/svg/chevron-right.svg
Does not affect the working, because both characters are flagged as bidirectional in Unicode. No changeset needed.
> chore: fix SVG title

- .changeset/lemon-cheetahs-live.md
- components/alert/README.md
- components/alert/src/_mixin.scss
- components/alert/src/index.scss
- components/alert/src/tokens.json
- packages/component-library-react/src/Alert.tsx
- packages/storybook-css/src/Alert.stories.tsx
- packages/storybook-css/src/Alert.tsx
- packages/storybook-react/src/stories/Alert.stories.tsx
- packages/web-component-library-stencil/src/components/alert.tsx
- proprietary/design-tokens/src/component/utrecht/alert.tokens.json
Refactor the Alert component for more consistent token names and use flex instead of grid layout. Adding support for content and message sections.
- Rename `utrecht.alert.icon.gap` to `utrecht.alert.column-gap`
- Add `utrecht.alert.message.row-gap` token
- Add `utrecht.alert.content.row-gap` token
- Add `utrecht.alert.icon.size` token
- Add `utrecht.alert.icon.inset-block-start` token
- Change implementation of layout from grid to flex
(_Totally didn't copy paste the changelog_)
> style: refactor alert design tokens

- package.json
Fixes the pipeline:
https://github.com/nl-design-system/utrecht/actions/runs/10472110363/job/29001119320#step:7:28
The following error occurs when a package referenced in a changeset cannot be found:
```
error TypeError: Cannot destructure property 'packageJson' of 'undefined' as it is undefined.
```
> ci: check changeset correctness in GitHub Actions as lint step

- .changeset/good-sport-resource.md
- components/backdrop/src/tokens.json
Fixed metadata for backdrop.
[Available tokens in Token Studio](https://docs.tokens.studio/available-tokens/available-tokens)
Not supported:
- `z-index`
- `animation-duration`
Supported:
`opacity`
> fix: metadata for backdrop

- .changeset/helpless-listen-perfect.md
- components/accordion/src/tokens.json
- Fixed metadata for `border-radius` token of accordion.
- Changend figma support value of `button.icon.background-color` form `true` to `false`.
- Added missing tokens and metadata for `accordion.section`
> fix: metadata for accordion

- .changeset/proud-ants-sing.md
- components/accordion/src/_mixin.scss
- components/accordion/src/tokens.json
- proprietary/design-tokens/src/component/utrecht/accordion.tokens.json
Deze tokens accordion header tokens die ik heb toegevoegd, zijn nodig om de white space tussen de expand button en de content weg te halen.
Die tokens waren er eerst wel voor dat we de html heading hadden toegevoegd.
> style: add header margin block tokens

- .changeset/am-gasp-major.md
- components/skip-link/src/tokens.json
- Added metadata for skip-link component.
- Added tokens
`utrecht.skip-link.focus.background-color` and `utrecht.skip-link.focus.color` because they were available in [Storybook](https://nl-design-system.github.io/utrecht/storybook/?path=/story/css_css-skip-link--design-tokens).
> feat: add metadata for skip-link component

- .changeset/star-honor-sin.md
- components/search-bar/src/_mixin.scss
- components/search-bar/src/tokens.json
- Added metadata for search bar tokens.
- Changed CSS variable name in mixin from `--utrecht-search-bar-hover-transform` to `--utrecht-search-bar-hover-scale` to align with the token name.
> feat: add metadata for search bar

- .changeset/scrap-meal-heal.md
- components/button/src/tokens.json
Changed value of `"nl.nldesignsystem.figma.supports-token"` from `true` to `false` as it's not used for the Figma component within the 'Voorbeeld' library.
> fix: metadata for button component

- .changeset/delicate-dark-coin.md
- components/link-social/src/tokens.json
- Added metadata for link-social tokens.
- Added missing token for `--utrecht-link-social-icon-size` variable which was found in the mixin.
- Changed order of tokens so they are easier to scan.
> feat: add metadata for link-social

- .changeset/dominant-first-poor.md
- components/form-toggle/src/_mixin.scss
Fixed form toggle token variable name te be in line with our naming convention.
`--utrecht-form-toggle-background-disabled-background-color` to `--utrecht-form-toggle-disabled-background-color`
> fix: form toggle token variable name

- .changeset/bee-baa-boop.md
- components/badge-list/src/_mixin.scss
- components/badge-list/src/tokens.json
- Renamed `utrecht-badge-list-item-margin-block` to `utrecht-badge-list-row-gap`.
- Renamed `utrecht-badge-list-item-margin-inline` to `utrecht-badge-list-column-gap`.
> fix: renamed badge-list spacing tokens

- .changeset/sheet-shock-round.md
- components/mapcontrolbutton/src/tokens.json
- Added metadata for mapcontrolbutton tokens.
- Added missing tokens for variables that were in the index.scss file.
- Removed the tokens `mapcontrolbutton.disabled.hover-background-color` and `mapcontrolbutton.primary-action.hover-background-color` as I assume it was a mistake.
- Could not find any mention of `mapcontrolbutton.primary-action*` tokens but kept them in there.
- Also wonder about the naming. Should it be mapcontrol-button? Anyway... kept it this way.
> feat: add metadata for mapcontrolbutton

- .changeset/stir-lake-route.md
- components/radio-button/src/tokens.json
- Added metadata for radio-button tokens.
- Added `margin-inline-end` token that was available in mixin.
- Reordered tokens in json for better scanning of tokens.
> feat: add metadata for radio-button

- .changeset/node-big-rock.md
- .changeset/textarea-quux-bar.md
- components/textarea/src/_mixin.scss
- components/textarea/src/tokens.json
- proprietary/design-tokens/src/component/utrecht/textarea.tokens.json
- Added metadata for textarea tokens.
- Renamed CSS variable in mixin `--utrecht-textarea-border-bottom-width` to `--utrecht-textarea-border-block-end-width`.
- Renamed CSS variable in mixin `--utrecht-textarea-invalid-border-bottom-width` to `--utrecht-textarea-invalid-border-block-end-width`.
- Added token and metadata for `utrecht.textarea.invalid.border-block-end-width`.
> feat: add metadata for textarea

- .changeset/idea-lie-shelf.md
- components/select/src/tokens.json
Not a fix but a feat, sorry.
Added token `select.invalid.border-block-end-width` to the json because it is available as CSS variable in the mixin.
> feat: add border-block-end-width token for invalid state

- .changeset/cheap-crown-linen.md
- components/toptask-link/src/tokens.json
- Added metadata for toptask-link tokens.
- Added missing tokens that were available as CSS variants in the mixin.
> feat: add metadata for toptask-link tokens

- .changeset/aap-noot-mies.md
- components/code-block/src/tokens.json
- components/code/src/tokens.json
- components/color-sample/src/tokens.json
- components/drawer/src/tokens.json
- components/pre-heading/src/tokens.json
@Rozerinay added new components to Figma. So Figma support for corresponding component tokens is now 'true'.
Changed value for Figma support metadata:
- Code block
- Code
- Color sample
- Drawer
- Pre heading
> fix: changed figma support value for roos components

- package.json
This missing configuration prevents `lint:changeset` to succeed and it blocks doing new releases.
> fix: copy new pnpm workspace settings to `package.json`

- .changeset/prickly-roses-cry.md
- .changeset/red-roses-blush.md
- .changeset/slimy-roses-scream.md
- .changeset/white-roses-shine.md
- components/button/src/_mixin.scss
- components/button/src/index.scss
- components/button/src/tokens.json
- packages/components-react/button-react/src/index.test.tsx
- packages/components-react/button-react/src/index.tsx
- packages/storybook-react/package.json
- packages/storybook-react/src/stories/Button.stories.tsx
- packages/storybook-web-component/src/Button.stories.tsx
- packages/web-component-library-stencil/src/components/button.tsx
- pnpm-lock.yaml
- proprietary/design-tokens/src/component/utrecht/button.tokens.json
Adds `utrecht-button-column-gap` with `__label` element. Also fixes the button stories missing CSS
Todo after feedback
> feat: add utrecht-button-column-gap

- .changeset/good-rice-cover.md
- components/number-badge/src/_mixin.scss
- components/number-badge/src/index.scss
- components/number-badge/src/tokens.json
- packages/storybook-css/src/NumberBadge.stories.tsx
Fixes #2480
https://github.com/nl-design-system/utrecht/blob/main/components/badge/src/_mixin.scss#L35-L43
> feat: add number badge border design tokens

- .changeset/purple-coins-change.md
- components/paragraph/src/html/_mixin.scss
- packages/storybook-html/src/Paragraph.stories.tsx
removed deprecated code for html paragraph
> chore: remove lead small paragraph

- .changeset/slow-drinks-applaud.md
- components/img/src/_mixin.scss
Doordat de height en width altijd op auto staan kun je de img size niet aanpassen: https://nl-design-system.github.io/utrecht/storybook/?path=/docs/css_css-img--docs
> fix: image width height auto

- packages/storybook-react/config/preview.tsx
The issue occurs only when you click the preview button to open the story on a separate page, outside of the iframe.
> fix(react-storybook): fix style issue

- packages/docusaurus/docs/componenten/icons/Iconen overzicht.mdx
> fix: icon docusaurus

- .changeset/large-berries-boil.md
- packages/web-component-library-stencil/src/components/data-list-actions.tsx
- packages/web-component-library-stencil/src/components/data-list-key.tsx
- packages/web-component-library-stencil/src/components/logo-button.tsx
- packages/web-component-library-stencil/src/components/number-badge.tsx
- packages/web-component-library-stencil/src/components/page-content.tsx
- packages/web-component-library-stencil/src/components/surface.tsx
Dank aan Harmen van der Spek voor de bug report!
> fix: avoid duplicate classes

- .changeset/clean-sloths-lick.md
- components/custom-checkbox/src/_mixin.scss
Het  voorkomt dat de checked image al inlaad zodat als je erop focused en de background color veranderd naar een donkere kleur dat de checkmark verschijnt zoals in purmerend
> fix: remove background image from custom checkbox focus styles

- .changeset/twenty-bees-train.md
- packages/components-react/listbox-react/src/index.test.tsx
- packages/components-react/listbox-react/src/index.tsx
> fix: avoid "list" role elements in Listbox

- README.md
- package.json
- packages/storybook-angular/package.json
Same as #2637, but without the lodash-es refactoring which gives (to me) unexplainable import errors in CI but not locally.
> ci: add `pnpm run build-vercel`

- .changeset/delay-mass-pole.md
- components/form-toggle/src/tokens.json
Weet niet hoe deze er tussendoor zijn geslipt, maar de tokens voor Form toggle worden (nog) niet in Figma gebruikt. Met deze PR wordt dat weer rechtgetrokken.
> fix: changed support token for form toggle

- .changeset/eighty-days-kiss.md
- .changeset/seven-toys-jam.md
- packages/build-utils-react/src/lib/configure.mjs
- packages/component-library-react/package.json
- packages/components-react/body-react/package.json
- packages/components-react/button-react/package.json
- packages/components-react/calendar-react/package.json
- packages/components-react/checkbox-group-react/package.json
- packages/components-react/checkbox-react/package.json
- packages/components-react/combobox-react/package.json
- packages/components-react/data-badge-react/package.json
- packages/components-react/fieldset-react/package.json
- packages/components-react/form-field-checkbox-react/package.json
- packages/components-react/form-field-description-react/package.json
- packages/components-react/form-field-error-message-react/package.json
- packages/components-react/form-field-react/package.json
- packages/components-react/form-label-react/package.json
- packages/components-react/link-react/package.json
- packages/components-react/listbox-react/package.json
- packages/components-react/nav-bar-react/package.json
- packages/components-react/page-body-react/package.json
- packages/components-react/page-footer-react/package.json
- packages/components-react/page-header-react/package.json
- packages/components-react/page-layout-react/package.json
- packages/components-react/radio-button-react/package.json
- packages/components-react/radio-group-react/package.json
- packages/components-react/root-react/package.json
- packages/components-react/select-combobox-react/package.json
- packages/components-react/textbox-react/package.json
While working on https://github.com/nl-design-system/rijkshuisstijl-community/issues/1094 I was running into vitest issues, because data-badge-react didn't have the exports field filled. 
I reran "pnpm run --recursive init", which added back the field and made some more changes. (I did not include whatever that command changed for packages/component-library-react, though.)
> fix: data-badge-react does not have exports field

- packages/build-utils-css/src/index.mjs
The build in `main` now sometimes fails (and currently fails) because the `dist/` dir doesn't exist.
> fix: avoid flaky builds, ensure output dir exists

- .changeset/angry-carpets-arrive.md
- packages/component-library-vue/src/DataListValue.vue
The DataListValue vue component checks if the value specified is empy, and if so shows a dash (-) to signify that there is no content. But because this check is only done on the initial render of the component, the empty state is not toggled whenever the value changes. By making the empty property computed, it is re-calculated whenever the value changes
> fix: make the empty state reactive in DataListValue.vue

- components/alert/src/_mixin.scss
- packages/component-library-react/src/Alert.tsx
- packages/storybook-css/src/Alert.tsx
- packages/web-component-library-stencil/src/components/alert.tsx
Previously, headers and paragraphs inserted into `<Alert>` components would not receive the `--utrecht-alert-color` token for their color properties. According to Figma designs, they should, so this PR fixes that.
See also; https://github.com/nl-design-system/rijkshuisstijl-community/issues/1692
> fix: use alert text color token

- .changeset/strong-pumas-draw.md
- components/textbox/src/_mixin.scss
Ik heb op de textbox de invalid selector veranderd naar user-invalid, zodat de invalid css pas toegepast word als de gebruiker interactie met de textbox heeft gehad.
> fix: change invalid selector to user-invalid in textbox

- packages/astro/astro.config.ts
The main branch deployment adds `/utrecht/` to its base url. The astro config was unable to handle that before. This should fix it.
1. Run `pnpm astro dev` to ensure it still works when running astro locally. Keeping in mind that resource URLs are all correct and loading (svgs, styles)
2. Run `BASE_URL=/utrecht/ pnpm astro dev` to test if all resource URLs are correct if there is a base URL like on the main branch deployment
> fix: astro base url

- packages/storybook-pdf/package.json
- pnpm-lock.yaml
There is a race condition introduced by storybook-pdf importing @utrecht/design-tokens before it finishes building sometimes. Adding it to the devDependencies should make sure it builds after.
> chore: add @utrecht/design-tokens to storybook-pdf dev dependencies to prevent race condition
