nl-design-system/utrecht

README.md

First pull request for feature branch.

docs: add Utrecht logo to storybook

---

README.md

Improved readme.md instructions.

Improved list layout and text for first setup.

---

proprietary/design-tokens/component/button.css
src/button/README.md
src/button/button-html.stories.mdx
src/button/button.stories.mdx
src/button/html.scss
src/button/style.css

Aan de button component heb ik de extra state `disabled` toegevoegd. Ik heb erop gelet dat de `:hover` state niet wordt gebruikt voor disabled buttons, dat zou er raar uitzien.

feat: disabled state for button

---

components/blockquote/README.md
components/form-label/README.md
components/heading/README.md
components/link/README.md
components/separator/README.md
components/unordered-list/README.md

Includes documentation for class names and design tokens of:
- blockquote
- form label
- headings
- link
- separator
- unordered list

docs: add pull requests description as basis for README

---

.github/dependabot.yml

ci: ignore webpack 5 until fully supported by Storybook

---

components/link/bem.scss
components/link/bem.stories.mdx
components/link/html.scss
components/link/html.stories.mdx

[Suggestie](https://twitter.com/asinnema/status/1413518305491628033) van @anneke.

feat: telephone link

---

components/menulijst/bem.css
components/menulijst/bem.scss
components/menulijst/bem.stories.mdx
components/menulijst/pijltje.svg
components/unordered-list/html.scss
packages/storybook/.storybook/main.js
packages/storybook/.storybook/preview.js

Menulist opgeschoond:
- markers verwijderd
- underline weg
- balk netter

Menulist markerremoval

---

proprietary/design-tokens/src/common/utrecht/focus.style-dictionary.json

Update styling focus (no background)

Update styling :focus

---

components/navigatie topnav/bem.scss

We need readable text, WCAG update

WCAG Update bem.scss

---

package-lock.json
packages/component-library-css/src/bem.scss

Er waren nog nieuwe componenten bijgekomen, maar die waren nog niet geïmporteerd.

Nieuwe bestanden toegevoegd

---

components/form-field-checkbox-group/README.md
components/form-field-checkbox-group/bem.css
components/form-field-checkbox-group/bem.stories.mdx

Simpele toevoeging van checkbox group gebaseerd op deradiobutton groep. Voor zien komen in de Huwelijksplanner.

🔨 checkbox groep toegevoegd

---

components/link/docs/ux-guidelines.md
components/link/docs/ux-guidelines.stories.mdx

🎉 Documentatie toegevoegd

---

components/form-field-textbox/stencil.stories.mdx
components/form-field-textbox/stencil.tsx
components/textbox/bem.stories.mdx
components/textbox/html.scss
components/textbox/readme.stories.mdx
components/textbox/stencil.stories.mdx
components/textbox/stencil.tsx

- `min`/`max`/`pattern`
- increase consistency between CSS/HTML/Web component and _Textbox_ and _Form field with textbox_.

feat: support more properties for textbox

---

components/button/docs/ux-guidelines.md
components/button/docs/ux-guidelines.stories.mdx
components/form-field-radio-group/docs/ux-guidelines.md
components/form-field-radio-group/docs/ux-guidelines.stories.mdx

Documentatie voor button en radio buttons.

⚡️ documentatie voor buttons en radio buttons

---

proprietary/design-tokens/src/brand/utrecht/typography.tokens.json

change font-lg to 18 and added font-4xl

New font sizes

---

components/mapcontrolbutton/bem.stories.mdx
components/toptask-link/README.md
components/toptask-link/bem.js
components/toptask-link/bem.scss
components/toptask-link/bem.stories.mdx
components/toptask-link/readme.stories.mdx
components/toptask-link/tokens.json
components/toptask-nav/README.md
components/toptask-nav/bem.js
components/toptask-nav/bem.scss
components/toptask-nav/bem.stories.mdx
components/toptask-nav/readme.stories.mdx
components/toptask-nav/tokens.json
proprietary/design-tokens/src/component/utrecht/toptask-link.tokens.json
proprietary/design-tokens/src/component/utrecht/toptask-nav.tokens.json

Implementatie van toptaken blok  #31

feat: toptask navigation

---

components/backdrop/README.md
components/backdrop/bem.js
components/backdrop/bem.scss
components/backdrop/bem.stories.mdx
components/backdrop/checkerboard.js
components/backdrop/readme.stories.mdx
components/backdrop/stencil.scss
components/backdrop/stencil.stories.mdx
components/backdrop/stencil.tsx
components/backdrop/tokens.json
packages/web-component-library-angular/src/index.module.ts
proprietary/design-tokens/src/component/utrecht/backdrop.tokens.json

First of the necessary parts for a modal dialog.

feat: backdrop component

---

components/navigatie sidenav/bem.scss
components/templates/contact-card-template/bem.scss

Not all regressions detected by Percy had been fixed before merging PR #522, hopefully this addresses those issues.

fix: regressions from spacing updates

---

components/heading/README.md
components/heading/design.md
components/heading/readme.stories.mdx

update readme for headings

---

components/navigatie sidenav/bem.scss

Update inline start menu underline

---

proprietary/design-tokens/src/brand/utrecht/typography.tokens.json

follow up to commit 8490d946d62e5271a12788798196ea19a3593f2a

style: remove Lucida as fallback font, use Arial

---

.github/dependabot.yml
.ncurc.major.js
package-lock.json
package.json

Update major versions

---

components/navigatie sidenav/bem.js
components/navigatie sidenav/bem.scss
components/navigatie sidenav/bem.stories.mdx
components/navigatie sidenav/stencil.tsx

fix: more accurate connection length in sidenav component

---

components/navigatie sidenav/bem.scss

style: margin separator from md to lg to align line with label for more overview, width set to 19rem.

style: sidenav margin en width update

---

README.md

In English for now. We might want to also translate this README later :)

docs: update root README with docusaurus

---

components/button-group/README.md
components/button-group/css/index.scss
components/button-group/css/stories/01-default.stories.mdx
components/button-group/css/stories/02-vertical.stories.mdx
components/button-group/css/stories/readme.stories.mdx
components/button-group/css/stories/tokens.stories.mdx
components/button-group/css/template.js
components/button-group/tokens.json
packages/component-library-css/src/bem.scss

feat: button group

---

components/link-button/README.md
components/link-button/css/index.scss
components/link-button/css/stories/01-default.stories.mdx
components/link-button/css/stories/readme.stories.mdx
components/link-button/css/stories/state.stories.mdx
components/link-button/css/template.js
packages/component-library-css/src/bem.scss

feat: Link button - button that looks like a link

---

.tokens.stylelintrc.json
package-lock.json
package.json
proprietary/design-tokens/.npmignore
proprietary/design-tokens/build-stylelint.mjs
proprietary/design-tokens/package.json

feat: script to generate stylelint rule to find undocumented CSS vars

---

components/link-social/css/index.scss
components/link-social/css/stories/tokens.stories.mdx
components/link-social/tokens.json
proprietary/design-tokens/src/component/utrecht/link-social.tokens.json

feat: improve link social component

---

components/toptask-nav/css/template.js
packages/storybook/stories/icon/icon-gallery.stories.mdx
proprietary/design-tokens/src/component/utrecht/toptask-link.tokens.json

change icon-size: value to 2,375rem (38px)

fix: toptask icon size

---

standalone/docusaurus/package-lock.json
standalone/docusaurus/package.json

Now you can use the following in `.mdx`:
```js
import { UtrechtIconAfval } from "@utrecht/web-component-library-react";
```
And:
```js
<UtrechtIconAfval />
```

build: make web components available in Docusaurus

---

packages/storybook-vue/src/stories/Button/Button.stories.mdx
packages/storybook-vue/src/stories/Button/ButtonApearance.stories.mdx
packages/storybook-vue/src/stories/Button/ButtonStates.stories.mdx
packages/storybook-vue/src/stories/Button/docs/accessibility.stories.mdx
packages/storybook-vue/src/stories/Button/docs/onderzoek.stories.mdx
packages/storybook-vue/src/stories/Button/docs/ux-guidelines.stories.mdx

docs: add code snippet to the button stories

---

.github/workflows/continuous-delivery.yml

add chromatic and rename steps for visual regression testing to include percy

ci: add push to chromatic to continuous integration step

---

packages/storybook-vue/config/.babelrc.json
packages/storybook-vue/package.json
packages/storybook-vue/src/index.ts
packages/storybook-vue/src/stories/Heading/Heading.stories.mdx
packages/storybook-vue/src/stories/Heading/tokens.stories.mdx

docs: add vue heading stories

---

packages/component-library-vue/src/UtrechtBadgeStatus.vue
packages/storybook-vue/config/preview.js
packages/storybook-vue/package.json
packages/storybook-vue/src/stories/Article/Article.stories.mdx
packages/storybook-vue/src/stories/Article/argsTypes.ts
packages/storybook-vue/src/stories/Article/tokens.stories.mdx
packages/storybook-vue/src/stories/BadgeStatus/BadgeStatus.stories.mdx
packages/storybook-vue/src/stories/BadgeStatus/BadgeStatusDefault.stories.mdx
packages/storybook-vue/src/stories/BadgeStatus/argTypes.ts
packages/storybook-vue/src/stories/BadgeStatus/tokens.stories.mdx
packages/storybook-vue/src/stories/Button/tokens.stories.mdx
packages/storybook-vue/src/stories/ButtonGroup/ButtonGroup.stories.mdx
packages/storybook-vue/src/stories/ButtonGroup/argsTypes.ts
packages/storybook-vue/src/stories/ButtonGroup/tokens.stories.mdx
packages/storybook-vue/src/stories/Checkbox/tokens.stories.mdx

fix: the badge status vue component class name & add some vue stories

---

packages/storybook-vue/src/stories/Link/Link.stories.mdx
packages/storybook-vue/src/stories/Paragraph/argTypes.ts

build: fix the storybook console warning issue

---

package-lock.json
packages/storybook/config/main.js
packages/storybook/package.json

https://storybook.js.org/docs/react/configure/images-and-assets#serving-static-files-via-storybook-configuration

build: use `main.js` to set the `staticDirs`

---

README.md

for providing us with a free starter plan of 35k snapshots each month in addition to our own paid license.

docs: credit chromatic

---

components/skip-link/README.md
components/skip-link/css/_mixin.scss
components/skip-link/css/index.scss
components/skip-link/css/stories/default.stories.mdx
components/skip-link/css/stories/readme.stories.mdx
components/skip-link/css/stories/rtl.stories.mdx
components/skip-link/css/stories/tokens.stories.mdx
components/skip-link/css/stories/visible-on-focus.stories.mdx
components/skip-link/css/story-template.jsx
components/skip-link/tokens.json
proprietary/design-tokens/src/component/utrecht/skip-link.tokens.json

There is some related documentation I have been working on in another repo, I want to import that markdown in this Storybook eventually: https://github.com/nl-design-system/documentatie/pull/85

feat: skip link component

---

.github/workflows/continuous-delivery.yml

https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#example-using-the-cache-action

ci: cache .npm/ directory in GitHub Actions

---

components/button/css/index.scss
components/button/css/story-template.jsx
components/common/focus/_mixin.scss
components/common/focus/tokens.json
proprietary/design-tokens/src/common/utrecht/focus.tokens.json
proprietary/design-tokens/src/component/utrecht/mapcontrolbutton.tokens.json

fix: disabled state in combination with focus, focus-visible and hover

---

proprietary/design-tokens/src/dark/common/tokens.json
proprietary/design-tokens/src/dark/component/tokens.json

style: DarkMode Styling update

style: darkmode Styling update

---

proprietary/design-tokens/src/brand/utrecht/color.tokens.json

style: more colors for darkmode

---

proprietary/design-tokens/src/component/den-haag/process-steps.tokens.json

green-30 look and feel, white markers, bigger substeps

style: restyling process-steps

---

packages/storybook-react/package.json
pnpm-lock.yaml

We need the new design tokens.
Before:
After:

build: update to latest Process Steps component

---

proprietary/design-tokens/src/brand/utrecht/icon.tokens.json

json file for icon-scale tokens

feat: new brand icon scale tokens

---

packages/component-library-react/src/BreadcrumbNav.test.tsx
packages/component-library-react/src/BreadcrumbNav.tsx

Eerste tests. We gaan deze week verder.

test: breadcrumb navigation

---

proprietary/design-tokens/src/common/utrecht/border.tokens.json

Extra new border tokens (brand ready)
- border-radius

style: new border-radius tokens

---

packages/component-library-react/package.json
packages/storybook-react/config/main.js
packages/storybook-react/config/preview.js
packages/storybook-react/package.json
pnpm-lock.yaml

docs: include Jest tests in React Storybook

---

proprietary/design-tokens/src/brand/utrecht/color.tokens.json
proprietary/design-tokens/src/dark/common/tokens.json
proprietary/design-tokens/src/dark/component/tokens.json

Styling update voor tokens voor drakmode:
- font
- background
- buttons, primary, secondary
- link
- Spotlight
- Formfield

style: darkmode tokens update

---

documentation/website/gebruikersonderzoek/research_0022.md

Aanpassing aan titel gedaan op verzoek Vincent van Beek.

docs(onderzoek): aanpassing titel onderzoek

---

components/select/css/_mixin.scss
components/textarea/css/_mixin.scss
components/textbox/css/_mixin.scss
proprietary/design-tokens/src/dark/component/tokens.json

style: fix invalid form control border-bottom

---

packages/component-library-react/src/StatusBadge.test.tsx
packages/component-library-react/src/StatusBadge.tsx
packages/component-library-react/src/css-module/StatusBadge.tsx
packages/component-library-react/src/css-module/index.ts

status badge component aangemaakt

feat: status badge react

---

documentation/website/huisstijl/_kleuren.mdx
proprietary/design-tokens/src/brand/utrecht/color.tokens.json

style: add secondary color tokens

---

components/form-control/tokens.json
components/textbox/css/_mixin.scss
components/textbox/tokens.json

line height token voor textbox

feat: new token voor line height

---

proprietary/design-tokens/src/background-image-icon.scss
proprietary/design-tokens/src/dark/index.scss
proprietary/design-tokens/src/index.scss
proprietary/design-tokens/src/style-dictionary-config-dark.js
proprietary/design-tokens/style-dictionary.config.json

https://kilianvalkhof.com/2023/css-html/root-isnt-global/

style: support design tokens in `::selection`

---

documentation/components/ExampleTokensCSS.jsx

docs: make CSS tokens example simpler to uncomment one token at a time

---

components/accordion/tokens.json

css tokens gefixed door extensions toe te voegen en css naar nl.nldesignsystem.css.property

fix: accordion tokens fixed

---

components/button-link/css/_mixin.scss
components/button/css/_mixin.scss
components/button/css/index.scss

style: support forced color mode for button

---

components/data-placeholder/README.md
components/data-placeholder/css/_mixin.scss
components/data-placeholder/css/index.scss
components/data-placeholder/tokens.json
components/index.scss
packages/component-library-react/src/DataPlaceholder.tsx
packages/component-library-react/src/css-module/DataPlaceholder.tsx
packages/component-library-react/src/css-module/index.ts
packages/component-library-react/src/index.ts
packages/storybook-react/src/stories/DataPlaceholder.stories.tsx
packages/storybook/stories/components/DataPlaceholder.stories.tsx
proprietary/design-tokens/src/component/utrecht/data-placeholder.tokens.json

feat: placeholder component

---

components/accordion/css/_mixin.scss
components/accordion/css/index.scss
components/accordion/tokens.json
proprietary/design-tokens/src/component/utrecht/accordion.tokens.json

-----
`utrecht-accordion__body` => `utrecht-accordion__panel` also add spacing tokens

feat: improve the accordion style 

---

packages/storybook/stories/icon/icon-gallery-socialmedia.stories.mdx
packages/storybook/stories/icon/icon-gallery.stories.mdx

x formerly known as twitter now categorized

docs: added x formerly known as twitter logo to gallery

---

packages/component-library-react/src/Calendar/index.tsx

fix: calendar dates should be selectable when not disabled

---

components/alert/tokens.json

I added the existing alert gap token to the alert documentation

docs: added alert gap token

---

packages/web-component-library-stencil/stencil.config.ts

https://stenciljs.com/docs/config-extras\#enableimportinjection

fix: stencil lazy loading in vite

---

components/custom-checkbox/css/_mixin.scss
components/form-fieldset/css/_mixin.scss
components/form-fieldset/tokens.json
components/heading-1/css/_mixin.scss
components/heading-2/css/_mixin.scss
components/heading-3/css/_mixin.scss
components/heading-4/css/_mixin.scss
components/heading-5/css/_mixin.scss
components/heading-6/css/_mixin.scss
components/pre-heading/css/_mixin.scss
components/radio-button/css/_mixin.scss
components/search-bar/css/_mixin.scss
components/search-bar/tokens.json
components/templates/contact-card-template/css/index.scss
proprietary/design-tokens/src/brand/utrecht/typography.tokens.json
proprietary/design-tokens/src/component/utrecht/checkbox.tokens.json
proprietary/design-tokens/src/component/utrecht/form-fieldset.tokens.json
proprietary/design-tokens/src/component/utrecht/heading-5.tokens.json
proprietary/design-tokens/src/component/utrecht/heading-6.tokens.json
proprietary/design-tokens/src/component/utrecht/pre-heading.tokens.json
proprietary/design-tokens/src/component/utrecht/radio-button.tokens.json
proprietary/design-tokens/src/component/utrecht/search-bar.tokens.json
proprietary/design-tokens/src/index.scss

Set uppercase to none and removed some uppercases values Size change of Radio en Checkbox to 22px and border 2px

style: radio, Checkbox and uppercase changes

---

components/breadcrumb/css/_mixin.scss
components/breadcrumb/css/index.scss
components/breadcrumb/tokens.json
packages/component-library-react/package.json
packages/component-library-react/src/BreadcrumbNav.test.tsx
packages/component-library-react/src/BreadcrumbNav.tsx
packages/component-library-react/src/css-module/index.ts
packages/component-library-react/src/index.ts
packages/storybook-react/package.json
packages/storybook-react/src/stories/BreadcrumbNav.stories.tsx
pnpm-lock.yaml
proprietary/design-tokens/src/component/utrecht/breadcrumb.tokens.json

- Added support for the `customLink` property in the `BreadcrumbLink` component.
- Developers can now provide a custom Link component to be used instead of the default Link.
- Example usage:
```jsx
import { BreadcrumbLink } from '@utrecht/design-system';
import Link from 'next/link';  
//or 
// import { Link } from "gatsby"
const DemoComponent = () => {
return (
<BreadcrumbNav>
<BreadcrumbLink customLink={Link} className="utrecht-link"  rel="home" href="/" index={0}>Home</BreadcrumbLink>
<BreadcrumbLink customLink={Link} className="utrecht-link" rel="products"  href="/products" index={1} >Products</BreadcrumbLink>
</BreadcrumbNav>
)
}
```
- Enabled specific styling (`utrecht-breadcrumb__link--current`) for current links.
- Enhances user experience by visually distinguishing the current …

feat(library-react): add customLink prop to BreadcrumbNav

---

components/form-field-error-message/css/_mixin.scss
components/form-field-error-message/tokens.json

style: support padding and background color in error message

---

components/drawer/README.md
components/drawer/css/_mixin.scss
components/drawer/css/index.scss
components/drawer/tokens.json
components/index.scss
packages/component-library-react/src/Drawer.tsx
packages/component-library-react/src/css-module/Drawer.tsx
packages/component-library-react/src/css-module/index.ts
packages/component-library-react/src/index.ts
packages/storybook-css/src/Drawer.stories.tsx
packages/storybook-react/src/stories/Drawer.stories.tsx
packages/storybook-web-component/src/Drawer.stories.tsx
packages/web-component-library-stencil/src/components.d.ts
packages/web-component-library-stencil/src/components/drawer.scss
packages/web-component-library-stencil/src/components/drawer.tsx
proprietary/design-tokens/src/component/utrecht/drawer.tokens.json

feat: drawer component

---

packages/component-library-react/src/Drawer.test.tsx
packages/component-library-react/src/Drawer.tsx

made a unit test for drawer component
and fixed a bug

fix: drawer unit test

---

packages/storybook/stories/developers/svg.stories.mdx

docs: fix MDX error in "Developers/SVG" page

---

package.json
packages/storybook-web-component/src/Textarea.stories.tsx
packages/web-component-library-stencil/package.json
packages/web-component-library-stencil/src/components.d.ts
packages/web-component-library-stencil/src/components/color-sample.tsx
packages/web-component-library-stencil/src/components/iban-data.tsx
packages/web-component-library-stencil/src/components/textarea.tsx
packages/web-component-library-stencil/stencil.config.ts
patches/@stencil__core@4.5.0.patch
pnpm-lock.yaml

Now `autoComplete` and `spellcheck` on `<textarea>` should work.

build: update to Stencil 4

---

components/breadcrumb-nav/css/_mixin.scss
components/breadcrumb-nav/tokens.json
proprietary/design-tokens/src/component/utrecht/breadcrumb-nav.tokens.json

feat: update breadcrumb style

---

.changeset/config.json
.github/workflows/continuous-delivery.yml
package.json
pnpm-lock.yaml

This has not been tested, hope it will work.
Resources I used:
- https://pnpm.io/using-changesets
- https://github.com/changesets/changesets#documentation

ci: add changeset publishing infrastructure

---

.github/workflows/block-autosquash-commits.yml

new action to block !squash and !fixup commits

feat: new action to fixup commits

---

pnpm-lock.yaml
proprietary/design-tokens/package.json

Let's check out what Chromatic thinks of Style Dictionary v4.

build: upgrade to Style Dictionary v4 prerelease

---

.github/dependabot.yml

Change interval from weekly -> monthly

build: update dependabot schedule

---

proprietary/design-tokens/src/component/utrecht/form-control.tokens.json
proprietary/design-tokens/src/dark/component/tokens.json

To improve understanding and accessibility, added this styling for the read-only variant of a text field control.

style: read-only styling added on form-control

---

packages/storybook/package.json
packages/storybook/stories/open-forms/BSN.stories.tsx
packages/storybook/stories/open-forms/Checkbox.stories.tsx
packages/storybook/stories/open-forms/Columns.stories.tsx
packages/storybook/stories/open-forms/Content.stories.tsx
packages/storybook/stories/open-forms/Currency.stories.tsx
packages/storybook/stories/open-forms/DateField.stories.tsx
packages/storybook/stories/open-forms/DateTimeField.stories.tsx
packages/storybook/stories/open-forms/EditGrid.stories.tsx
packages/storybook/stories/open-forms/Email.stories.tsx
packages/storybook/stories/open-forms/FieldSet.stories.tsx
packages/storybook/stories/open-forms/IBANField.stories.tsx
packages/storybook/stories/open-forms/LicensePlate.stories.tsx
packages/storybook/stories/open-forms/Number.stories.tsx
packages/storybook/stories/open-forms/PhoneNumberField.stories.tsx
packages/storybook/stories/open-forms/PostcodeField.stories.tsx
packages/storybook/stories/open-forms/Radio.stories.tsx
packages/storybook/stories/open-forms/Select.stories.tsx
packages/storybook/stories/open-forms/Selectboxes.stories.tsx
packages/storybook/stories/open-forms/Signature.stories.tsx
packages/storybook/stories/open-forms/StoryUtil.tsx
packages/storybook/stories/open-forms/Textarea.stories.tsx
packages/storybook/stories/open-forms/Textfield.stories.tsx
packages/storybook/stories/open-forms/TimeField.stories.tsx
packages/storybook/stories/open-forms/cosign.stories.tsx
pnpm-lock.yaml

Adds open forms components to storybook.
**Components to add**

feat: open formulier components

---

packages/storybook/stories/open-forms/Checkbox.stories.tsx
packages/storybook/stories/open-forms/Radio.stories.tsx
packages/storybook/stories/open-forms/Select.stories.tsx
packages/storybook/stories/open-forms/Selectboxes.stories.tsx

add voor open forms checked stories

feat: new checked stories

---

packages/storybook/stories/open-forms/Currency.stories.tsx

added 4 new stories to show different valuta options

feat: new valuta stories added

---

proprietary/design-tokens/src/component/utrecht/spotlight-section.tokens.json

style: lighter background spotlightsection

style: lighter background spotlightsection

---

proprietary/design-tokens/src/component/utrecht/paragraph.tokens.json

Changed the font size of the lead paragraph to utrecht.typography.scale.xl.font-size (20px) to enhance readability

style: lead paragraph more important

---

components/table/css/index.scss
packages/component-library-react/src/TableContainer.test.tsx
packages/component-library-react/src/TableContainer.tsx
packages/component-library-react/src/css-module/TableContainer.tsx
packages/component-library-react/src/css-module/index.ts
packages/component-library-react/src/index.ts
packages/storybook-react/src/stories/Accordion.stories.tsx

new table container component added for the inline scroll

feat: table container component add

---

proprietary/design-tokens/src/brand/utrecht/color.tokens.json
proprietary/design-tokens/src/component/utrecht/button.tokens.json

style: button active state

---

packages/storybook/stories/open-forms/BSN.stories.tsx
packages/storybook/stories/open-forms/Checkbox.stories.tsx
packages/storybook/stories/open-forms/Currency.stories.tsx
packages/storybook/stories/open-forms/DateField.stories.tsx
packages/storybook/stories/open-forms/DateTimeField.stories.tsx
packages/storybook/stories/open-forms/Email.stories.tsx
packages/storybook/stories/open-forms/IBANField.stories.tsx
packages/storybook/stories/open-forms/LicensePlate.stories.tsx
packages/storybook/stories/open-forms/Number.stories.tsx
packages/storybook/stories/open-forms/PhoneNumberField.stories.tsx
packages/storybook/stories/open-forms/PostcodeField.stories.tsx
packages/storybook/stories/open-forms/Radio.stories.tsx
packages/storybook/stories/open-forms/Select.stories.tsx
packages/storybook/stories/open-forms/Selectboxes.stories.tsx
packages/storybook/stories/open-forms/Textarea.stories.tsx
packages/storybook/stories/open-forms/Textfield.stories.tsx
packages/storybook/stories/open-forms/TimeField.stories.tsx
packages/storybook/stories/open-forms/cosign.stories.tsx

add disable stories to open forms components

feat: add disabled stories for OpenForms components

---

proprietary/design-tokens/src/component/utrecht/unordered-list.tokens.json

style: more readable listing

---

proprietary/design-tokens/src/component/utrecht/heading-1.tokens.json

style: h1 bigger 4xl font-size

style: h1 bigger 4xl font-size

---

components/code-block/css/_mixin.scss
components/code/css/_mixin.scss
packages/storybook-css/src/Code.stories.tsx

Dit zou de font-size van code snippets in headings van NL Design System website moeten helpen fixen.

style: more resilient font size for code

---

.changeset/light-dodos-rest.md
components/package.json
components/rollup.config.mjs
pnpm-lock.yaml

The `copy` command didn't seem to work reliably. Switching to making two builds instead, much easier and pretty fast anyway.

fix: restore missing `dist/` directory to @utrecht/components

---

.changeset/healthy-planets-taste.md
packages/component-library-react/src/Blockquote.test.tsx
packages/component-library-react/src/Blockquote.tsx
packages/component-library-react/src/css-module/Blockquote.tsx
packages/component-library-react/src/css-module/index.ts
packages/component-library-react/src/index.ts
packages/storybook-react/package.json
packages/storybook-react/src/stories/Blockquote.stories.tsx
pnpm-lock.yaml

[Blockquote in Storybook React](https://utrecht-git-feat-blockquote-react-nl-design-system.vercel.app/storybook-react/?path=%2Fstory%2Freact-blockquote--default)

feat: add Blockquote component for React

---

.eslintignore
.github/workflows/continuous-delivery.yml
.gitignore
.prettierignore
.stylelintignore
packages/component-library-angular/package.json
packages/component-library-react/package.json
packages/component-library-react/packages/button-react/package.json
packages/component-library-react/packages/calendar-react/package.json
packages/component-library-vue/package.json

Ik heb Codecov toegang gegeven tot nl-design-system/utrecht en ik heb de CODECOV_TOKEN ingesteld als secret

ci: enable code coverage with Codecov.com

---

.changeset/een-twee-drie.md
components/accordion/src/tokens.json

Add metadata for Accordion tokens.

feat: add metadata for accordion

---

.changeset/april-maart-mei.md
components/calendar/src/tokens.json

Added metadata for calendar tokens.

feat: add metadata for calendar

---

.changeset/approval-acquaintance-degree.md
.changeset/vier-vijf-zes.md
components/alert/src/tokens.json

feat: add metadata for alert

---

.changeset/layer-care-casualty.md
components/badge-status/src/tokens.json

Added metadata for badge status.

feat: add metadata for badge status

---

packages/storybook-css/src/ColorSample.stories.tsx

https://github.com/nl-design-system/utrecht/issues/2041 Sluit deze issue. (ik kan de issue niet linken dus ik zet het hier neer)

feat: add color sample story to css storybook

---

.changeset/declaration-stimulation-respectable.md
components/form-label/src/tokens.json

Added metadata for form-label tokens.

feat: add metadata for form-label

---

.changeset/bullet-instrument-gasp.md
components/form-toggle/src/tokens.json

Added metadata for form-toggle tokens.

feat: add metadata for form-toggle

---

.changeset/favourite-excavate-sleep.md
components/form-field-error-message/src/tokens.json

Added metadata for form-field-error-message tokens.

feat: add metadata for form-field-error-message

---

.changeset/koek-cake-beschuit.md
components/article/src/tokens.json

feat: add metadata for article

---

.changeset/reform-cooperate-runner.md
components/badge-data/src/tokens.json

Added metadata for badge data.

feat: add metadata for badge data

---

.changeset/assume-die-test.md
components/badge/src/tokens.json

feat: add metadata for badge

---

.changeset/spare-be-bible.md
components/blockquote/src/tokens.json

Added metadata for blockquote.

feat: add metadata for blockquote

---

.changeset/forecast-laborer-fossil.md
components/breadcrumb-nav/src/tokens.json

Add metadata for breadcrumb-nav.

feat: add metadata for breadcrumb-nav

---

.changeset/invasion-shell-confine.md
components/button/src/tokens.json

- Added metadata for button.
- Fixed wrong syntax for border-width.

feat: add metadata for button

---

.changeset/bed-warrant-doubt.md
components/button-group/src/tokens.json

Added metadata for buttongroup.

feat: add metadata for button group

---

.changeset/page-talk-enter.md
components/code/src/tokens.json

Added metadata for code tokens.

feat: add metadata for code

---

.changeset/safari-criminal-percent.md
components/checkbox/src/tokens.json

Added metadata for checkbox tokens.

feat: add metadata for checkbox

---

.changeset/particular-activate-literature.md
components/badge-list/src/tokens.json

feat: add metadata for badge list

---

.changeset/goud-zilver-brons.md
components/alert-dialog/src/tokens.json

Added metadata for alert-dialog

feat: add metadata for alert-dialog

---

.changeset/halt-patrol-physical
components/code-block/src/tokens.json

Added metadata for code-block tokens.

feat: add metadata for code-block

---

.changeset/cute-lane-amuse.md
components/color-sample/src/tokens.json

Added metadata for color-sample tokens.

feat: add metadata for color sample

---

.changeset/censorship-pursuit-paper.md
components/column-layout/src/tokens.json

Added metadata for column-layout tokens.

feat: add metadata for column-layout

---

.changeset/favour-survivor-exchange.md
components/data-list/src/tokens.json

Added metadata for data-list tokens.

feat: add metadata for data-list

---

.changeset/carbon-prescription-sigh.md
components/digid-button/src/tokens.json

Added metadata for digid-button tokens.

feat: add metadata for digid-button

---

.changeset/witch-process-discovery.md
components/data-placeholder/src/tokens.json

Added metadata for data-placeholder tokens.

feat: add metadata for data-placeholder

---

.changeset/green-toll-sight.md
components/document/src/tokens.json

Added metadata for document tokens.

feat: add metadata for document

---

.changeset/tie-proclaim-satellite.md
components/emphasis/src/tokens.json

Added metadata for emphasis tokens.

feat: add metadata for emphasis

---

.changeset/hunting-grimace-cultivate.md
components/figure/src/tokens.json

Add metadata for figure tokens.

feat: add metadata for figure

---

.changeset/bitter-timetable-tape.md
components/heading/src/tokens.json

Added metadata for heading tokens.

feat: add metadata for heading

---

.changeset/example-nail-pool.md
components/heading-group/src/tokens.json

Added metadata for heading-group tokens.

feat: add metadata for heading-group

---

.changeset/instinct-complication-commission.md
components/heading-1/src/tokens.json
components/heading-2/src/tokens.json
components/heading-3/src/tokens.json
components/heading-4/src/tokens.json
components/heading-5/src/tokens.json
components/heading-6/src/tokens.json

Added metadata for headings 1 to 6 tokens.

feat: add metadata for headings 1 to 6

---

.changeset/path-formal-rotate.md
components/icon/src/tokens.json

Added metadata for icon tokens.

feat: add metadata for icon

---

.changeset/fun-precedent-duck.md
components/index-char-nav/src/tokens.json

Added metadata for index-char-nav tokens.

feat: add metadata for index-char-nav

---

.changeset/bill-low-novel.md
components/link/src/tokens.json

---
"@utrecht/link-css": minor
---
Added metadata for link tokens.

feat: add metadata for link

---

.changeset/belt-tap-transport.md
components/link-list/src/tokens.json

Added metadata for link-list tokens.

feat: add metadata for link-list

---

.changeset/representative-relieve-ask.md
components/form/src/tokens.json

Added metadata for form tokens.

feat: add metadata for form

---

.changeset/tile-hiccup-chimney.md
components/focus-ring/src/tokens.json

Added metadata for focus-ring tokens.

feat: add metadata for focus-ring

---

.changeset/sentence-quaint-wait.md
components/drawer/src/tokens.json

Added metadata for drawer tokens.

feat: add metadata for drawer

---

.changeset/ruin-mail-vein.md
components/ordered-list/src/tokens.json

Added metadata for ordered-list tokens.

feat: add metadata for ordered-list

---

.changeset/knock-warn-sink.md
components/number-data/src/tokens.json

Added metadata for number-data tokens.

feat: add metadata for number-data

---

.changeset/yard-giant-stir.md
components/nav-bar/src/tokens.json

Added metadata for nav-bar tokens.

feat: add metadata for nav-bar

---

components/mark/src/tokens.json
war-seize-heat.md

Added metadata for mark tokens.

feat: add metadata for mark

---

.changeset/abnormal-cassette-explicit.md
components/logo/src/tokens.json

Added metadata for logo tokens.

feat: add metadata for logo

---

.changeset/sell-slice-solo.md
components/logo-image/src/tokens.json

Added metadata for logo-image tokens.

feat: add metadata for logo-image

---

.changeset/year-recover-mouse.md
components/calendar/src/tokens.json

Changed figma-support value for calendar tokens.

fix: changed figma support value for calendar

---

.changeset/official-scale-fine.md
components/list-social/src/tokens.json

Added metadata for list-social tokens.

feat: add metadata for list-social

---

.changeset/government-belt-word.md
components/form-field/src/tokens.json

Added metadata for form-field tokens.

feat: add metadata for form-field

---

.changeset/column-yearn-declaration.md
components/form-field-description/src/tokens.json

Added metadata for form-field-description tokens.

feat: add metadata for form-field-description

---

.changeset/union-pop-block.md
components/pre-heading/src/tokens.json

Added metadata for pre-heading tokens.

feat: add metadata for pre-heading

---

.changeset/ideal-shout-poll.md
components/paragraph/src/tokens.json

Added metadata for paragraph tokens.

feat: add metadata for paragraph

---

.changeset/grain-break-joke.md
components/page-header/src/tokens.json
components/pagination/src/tokens.json

Added metadata for pagination tokens.

feat: metadata for pagination

---

.changeset/play-bag-tear.md
components/page-footer/src/tokens.json

Added metadata for page-footer tokens.

feat: add metadata for page-footer

---

components/page/src/tokens.json
tip-chin-sum.md

Added metadata for page tokens.

feat: add metadata for page

---

.changeset/hot-spill-sick.md
components/select/src/tokens.json

- Added metadata for select
- Changed syntax for background-image token

feat: add metadata for select

---

.changeset/commission-nose-premium.md
components/form-control/src/tokens.json
components/form-field/src/tokens.json

Added metadata for form-control tokens.

feat: add metadata for form control

---

.changeset/text-even-stake.md
components/rich-text/src/tokens.json

Added metadata for rich text tokens.

feat: add metadata for rich text

---

.changeset/stock-solve-cow.md
components/page-header/src/tokens.json

Added metadata for page-header tokens.

feat: add metadata for page-header

---

.changeset/team-grant-thaw.md
components/page-content/src/tokens.json

Added metadata for page-content tokens.

feat: add metadata for page-content

---

.changeset/disco-sum-gate.md
components/map-marker/src/tokens.json

Added metadata for map-marker tokens.

feat: add metadata for map-marker

---

components/process-steps/src/tokens.json

Added metadata for process-steps tokens.

feat: add metadata for process-steps

---

.changeset/piano-arrow-level.md
components/separator/src/tokens.json

feat: add metadata for separator

---

.changeset/load-agent-drink.md
components/surface/src/tokens.json

Added metadata for surface tokens

feat: add metadata for surface

---

.changeset/long-post-creed.md
components/table/src/tokens.json

- Added metadata for table tokens.
- Added missing tokens that were available as CSS variants in the mixin.

feat: add metadata for table

---

.changeset/worth-bird-suite.md
components/toptask-nav/src/tokens.json

Added metadata for toptask-nav tokens.

feat: add metadata for toptask-nav tokens

---

.changeset/wake-craft-gun.md
components/vega-visualization/src/tokens.json

Added metadata for vega-visualization tokens.

feat: add metadata for vega-visualization

---

.changeset/torch-air-rub.md
components/spotlight-section/src/tokens.json

- Added metadata for spotlight section tokens.
- Added missing tokens that were available in mixin.

feat: add metadata for spotlight section

---

.changeset/salon-era-pest.md
components/unordered-list/src/tokens.json

Added metadata for unordered list tokens.

feat: add metadata for unordered-list

---

.changeset/weak-olives-collect.md
packages/component-library-react/src/NavList.test.tsx
packages/component-library-react/src/NavList.tsx
packages/component-library-react/src/NavListLink.test.tsx
packages/component-library-react/src/NavListLinkButton.test.tsx

Draft PR om Chromatic screenshots te vermijden.

feat: improve React NavList with restProps/forwardRef/className support

---

.changeset/tough-eggs-do.md
components/radio-button/src/_mixin.scss

fix: radio button disabled fallback variables

---

.changeset/big-three-ape.md
components/mark/src/tokens.json

Changed value for Figma support metadata.

fix: changed figma support value for mark

---

.changeset/fuzzy-ears-occur.md
.changeset/rotten-crews-brake.md
.changeset/serious-tomatoes-shake.md
packages/component-library-pdf/src/FormFieldTextarea.test.tsx
packages/component-library-react/src/FormFieldTextarea.test.tsx
packages/component-library-react/src/FormFieldTextarea.tsx
packages/component-library-react/src/Textarea.test.tsx
packages/component-library-react/src/Textarea.tsx
packages/component-library-react/src/css-module/FormFieldTextarea.tsx
packages/component-library-react/src/css-module/index.ts
packages/component-library-react/src/index.ts
packages/storybook-pdf/src/FormFieldTextarea.stories.tsx
packages/storybook-react/src/stories/FormFieldTextarea.stories.tsx

feat: add FormFieldTextarea component in React

---

.changeset/tender-crabs-love.md
packages/components-react/form-field-checkbox-react/src/index.test.tsx
packages/components-react/form-field-checkbox-react/src/index.tsx

fix: correct TypeScript definitions for `FormFieldCheckbox` event handlers

---

packages/storybook-react/src/stories/prototype-src/index.css

fix: workaround invalid textarea styling

fix: workaround invalid textarea styling

---

packages/storybook-react/src/stories/prototype-src/index.css

fix: form field description max inline size

fix: form field description max inline size

---

.changeset/smart-beers-begin.md
packages/components-react/radio-group-react/src/index.tsx

fix: pass required prop to radio group

fix: pass required prop to radio group

---

packages/storybook-react/src/stories/prototype-klachtenformulier-scenario-a/FormPage2.stories.tsx
packages/storybook-react/src/stories/prototype-klachtenformulier-scenario-a/FormPage3.stories.tsx
packages/storybook-react/src/stories/prototype-klachtenformulier-scenario-b/FormPage2.stories.tsx
packages/storybook-react/src/stories/prototype-klachtenformulier-scenario-b/FormPage3.stories.tsx

Kleine tekstuele aanpassingen in klachtenformulier templates naar aanleiding van tekst review met copywriters van gemeente Amsterdam

fix: text aangepast na taal check

---

.changeset/copy-cat-code.md
README.md
packages/component-library-react/package.json
packages/component-library-react/src/ButtonGroup.tsx
packages/component-library-react/src/css-module/ButtonGroup.tsx
packages/components-react/button-group-react/.eslintrc.json
packages/components-react/button-group-react/babel.config.cjs
packages/components-react/button-group-react/jest.config.mjs
packages/components-react/button-group-react/package.json
packages/components-react/button-group-react/rollup.config.mjs
packages/components-react/button-group-react/src/css.tsx
packages/components-react/button-group-react/src/index.test.tsx
packages/components-react/button-group-react/src/index.tsx
packages/components-react/button-group-react/src/insert-style.ts
packages/components-react/button-group-react/tsconfig.build.json
packages/components-react/button-group-react/tsconfig.json
packages/components-react/button-group-react/tsconfig.test.json
pnpm-lock.yaml

Based on the creation of the separate Button: https://github.com/nl-design-system/utrecht/commit/1e757386e3cfbaf0efa98a2ef8b9d19536564046#diff-e2954b558f2aa82baff0e30964490d12942e0e251c1aa56c3294de6ec67b7cf5

feat: add button-group-react package

---

packages/storybook-react/src/stories/prototype-src/FontTester.tsx

feat: letter-spacing option

---

packages/storybook-react/src/stories/prototype-src/FontTester.tsx

fix: fira sans update

---

packages/storybook-react/src/stories/prototype-src/FontTester.tsx

feat: new font types in switcher

feat: new font types in switcher

---

packages/storybook-react/package.json
packages/storybook-react/src/stories/open-forms/FormStep.stories.tsx
packages/storybook-react/src/stories/open-forms/StoryUtil.tsx
pnpm-lock.yaml

[issue](https://github.com/frameless/strapi/issues/1086)
Link naar de Openforms [storybook](https://utrecht-git-integrate-the-form-step-int-54b64c-nl-design-system.vercel.app/storybook-react/index.html?path=/docs/open-forms-formstep--docs)

docs(storybook-react): add FormStep to storybook

---

packages/storybook-react/src/stories/font-examples/paspoort.stories.tsx
packages/storybook-react/src/stories/prototype-src/ContentPaspoort.tsx
packages/storybook-react/src/stories/prototype-src/NotoSwitcher.js
packages/storybook-react/src/stories/prototype-src/index.css

fix: font research prototype

---

.changeset/fuzzy-bats-rest.md
.changeset/giant-mirrors-cover.md
.changeset/nervous-rats-speak.md
.changeset/sweet-rings-join.md
.changeset/witty-trainers-fry.md
components/accordion/src/_mixin.scss
components/accordion/src/index.scss
components/accordion/src/tokens.json
packages/component-library-react/src/Accordion.tsx
packages/storybook-react/src/stories/Accordion.stories.tsx
proprietary/design-tokens/src/component/utrecht/accordion.tokens.json

- [Figma link](https://www.figma.com/design/UXIHcIurAD8hyoBWx4hDBV/NLDS---Gemeente-Utrecht---Bibliotheek?node-id=1261-4784&p=f&t=pzBK3YUk6XgRaS9x-0)
- [Issue link](https://github.com/frameless/strapi/issues/1122)

feat(accordion-css): add support for Utrecht Municipality's new accordion style
